In [2]:
import numpy as np
import re
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.utils import to_categorical

# Load the text file
with open(r"C:\Users\Happy\OneDrive\Pictures\Screenshots\rnntext.txt", 'r') as file:
    text = file.read()

# Clean and preprocess
text = text.lower()
text = re.sub(r'[^a-zA-Z0-9\s]', '', text)
words = text.split()

# Tokenize and create sequences
sequence_length = 4
tokenizer = Tokenizer()
tokenizer.fit_on_texts([text])

sequences = []
for i in range(sequence_length, len(words)):
    seq = words[i-sequence_length:i+1]
    sequences.append(seq)

sequences = tokenizer.texts_to_sequences(sequences)
sequences = np.array(sequences)

X, y = sequences[:, :-1], sequences[:, -1]
y = to_categorical(y, num_classes=len(tokenizer.word_index) + 1)


In [7]:
sequences[0]

array([89,  1, 46, 90, 91])

In [8]:
X

array([[ 89,   1,  46,  90],
       [  1,  46,  90,  91],
       [ 46,  90,  91,  92],
       ...,
       [ 60,   3,  42,  18],
       [  3,  42,  18, 363],
       [ 42,  18, 363,   1]])

In [33]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense,GRU



In [34]:
vocab_size = len(tokenizer.word_index) + 1
embedding_dim = 50



In [36]:
model = Sequential()
model.add(Embedding(vocab_size, embedding_dim, input_length=sequence_length-1))
model.add(GRU(50))
model.add(Dense(50, activation='relu'))
model.add(Dense(vocab_size, activation='softmax'))



In [37]:

model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

model.fit(X, y, epochs=100, verbose=2)

Epoch 1/100
24/24 - 5s - 222ms/step - accuracy: 0.0535 - loss: 5.8908
Epoch 2/100
24/24 - 0s - 7ms/step - accuracy: 0.0816 - loss: 5.8179
Epoch 3/100
24/24 - 0s - 7ms/step - accuracy: 0.0816 - loss: 5.4459
Epoch 4/100
24/24 - 0s - 7ms/step - accuracy: 0.0816 - loss: 5.2129
Epoch 5/100
24/24 - 0s - 7ms/step - accuracy: 0.0816 - loss: 5.1415
Epoch 6/100
24/24 - 0s - 7ms/step - accuracy: 0.0816 - loss: 5.0764
Epoch 7/100
24/24 - 0s - 7ms/step - accuracy: 0.0816 - loss: 5.0310
Epoch 8/100
24/24 - 0s - 7ms/step - accuracy: 0.0816 - loss: 4.9690
Epoch 9/100
24/24 - 0s - 7ms/step - accuracy: 0.0829 - loss: 4.9231
Epoch 10/100
24/24 - 0s - 7ms/step - accuracy: 0.0842 - loss: 4.8530
Epoch 11/100
24/24 - 0s - 7ms/step - accuracy: 0.0829 - loss: 4.7753
Epoch 12/100
24/24 - 0s - 7ms/step - accuracy: 0.0869 - loss: 4.6748
Epoch 13/100
24/24 - 0s - 7ms/step - accuracy: 0.0922 - loss: 4.5432
Epoch 14/100
24/24 - 0s - 7ms/step - accuracy: 0.1043 - loss: 4.4133
Epoch 15/100
24/24 - 0s - 7ms/step - accu

In [38]:
len(sequences)/50

14.96

In [44]:
def predict_next_word(model, tokenizer, text, sequence_length):
    text = text.lower()
    text = re.sub(r'[^a-zA-Z0-9\s]', '', text)
    words = text.split()
    print(words)
    sequence = tokenizer.texts_to_sequences([words])
    print(sequence)
    sequence = np.array(sequence[-sequence_length+1:])
    print(sequence)
    predicted = model.predict(sequence)
    predicted_word_index = np.argmax(predicted, axis=1)[0]
    print(predicted_word_index)
    for word, index in tokenizer.word_index.items():
        if index == predicted_word_index:
            return word

text = "The villagers noticed him immediately for in"
predicted_word = predict_next_word(model, tokenizer, text, sequence_length)
print(f"Predicted next word: '{predicted_word}'")


['the', 'villagers', 'noticed', 'him', 'immediately', 'for', 'in']
[[1, 13, 205, 14, 206, 21, 6]]
[[  1  13 205  14 206  21   6]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step
2
Predicted next word: 'a'
